branches:
  only:
    - master

language: android
jdk: oraclejdk7
env:
  global:
  - secure: JAdhNlGIAHXv0VT0D1IuOZaWbZNvwJn1pruP79wvlqMJwhWq+xVMaCLWtlm3YsbYdkGIYPVYbX5UL6paF0lUbJNeQe20XE7pCMd+pukIsuWXyWuMp020BF2D3hR4hQypPr4PDqdx2sLXCyvUMsR7ZUAEnpqBZN0UsFMcUOFXqmI=
  - secure: Dj80D6RHg1tqSfrnS2ySyBt7MTi6D57FwQC3wTnSgKeSTFsILGMVQYLeXZ7KXa8lhiaD5ZkGj/cIUp8VPGVEpb2bw48lyW7GJYlQhxK8dF3qZ/q8JwAsQ+x6YeBkW8V7nTRlAeK1yMiZl5aRz/t9GPHnipU8m2/0bEwqOukCbRw=

android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - android-20
    - build-tools-20.0.0

install:
  - ./gradlew dependencies

script:
  - ./gradlew build

after_success:
  - ./gradlew uploadArchives